### ISSUE TITLE
ICS form repo

### ISSUE THREAD

**Issue by kerryhatcher** [neteoc/neteoc-ui#55]
Need to have a place where users could search for and download PDF ICS forms

Also would be nice if a user could have to option to have applicable fields automatically filled out based on context info.

**Comment by rachelpatterson86** [comment]
We can look at WebMerge. They pretty much auto fill docs. Used it at my previous place. Nicely documented. Not sure how expansive their free plan is though.
  
https://www.webmerge.me/register?plan=free
https://www.webmerge.me/developers
